name: 'sync-s3-action'
description: 'get/put files from/to S3'
author: 'Tom Brus'

inputs:
  # tokens ================================================================
  trigger_token:
    description: 'the github token (used for retriggering other actions)'
    required: true
  access_key:
    description: 'the AWS or Scaleway ACCESS_KEY (used to access S3)'
    required: true
  secret_key:
    description: 'the AWS or Scaleway SECRET_KEY (used to access S3)'
    required: true

  # required ================================================================
  cmd:
    description: 'the direction of the copy: "put" or "get"'
    required: true
  bucket:
    description: 'the s3 bucket'
    required: true

  # locations ================================================================
  local_dir:
    description: 'the local dir to copy from/to'
    required: true
  s3_dir:
    description: 'the s3 remote dir to copy to/from'
    required: false
  s3_dir_branched:
    description: 'the s3 remote dir to copy to/from, extended with $GITHUB_REPOSITORY and the current branch, also honor trigger files'
    required: false

  # optional ================================================================
  host:
    description: 'the s3 host (defaults to Scaleway: https://s3.$region.scw.cloud)'
    required: false
  region:
    description: 'the s3 region'
    required: false
    default: "nl-ams"
  trace:
    description: 'set this to "true" if you would like bash-tracing'
    required: false
    default: "false"

runs:
  using: 'composite'
  steps:
    - shell: bash
      id: main
      run: |
        set -euo pipefail
        [[ "${{inputs.trace}}" == "true" ]] && set -x

        . "${{github.action_path}}/buildtoolsMeme.sh" "${{github.token}}" ""
        . "${{github.action_path}}/functions.sh"

        main \
          "${{inputs.access_key}}"      \
          "${{inputs.secret_key}}"      \
          "${{inputs.trigger_token}}"   \
          "${{inputs.cmd}}"             \
          "${{inputs.bucket}}"          \
          "${{inputs.local_dir}}"       \
          "${{inputs.s3_dir}}"          \
          "${{inputs.s3_dir_branched}}" \
          "${{inputs.host}}"            \
          "${{inputs.region}}"
