name: test
on:
  push
jobs:
  test:
    runs-on: [ubuntu-latest]
    steps:
      - name: "checkout"
        uses: actions/checkout@v1

      - name: "setup JDK"
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: "test: prepare"
        run: |
          mkdir test-dir-put
          echo test123 > test-dir-put/test123
          echo "::set-env name=TEMP_BUCKET::mvg-test-temp-$RANDOM"
          printf 'artifacts=("org.modelingvalue testing123 47.11 jar j--")\n' > project.sh

      - name: "test: put with branch dir"
        uses: ModelingValueGroup/sync-s3-action@master
        with:
          token          : "${{ secrets.GITHUB_TOKEN }}"
          trigger_token  : "${{ secrets.RETRIGGER_TOKEN }}"
          access_key     : "${{ secrets.SCALEWAY_ACCESS_KEY }}"
          secret_key     : "${{ secrets.SCALEWAY_SECRET_KEY }}"
          bucket         : "mvg-test-perma"
          cmd            : "put"
          local_dir      : "test-dir-put"
          s3_dir_branched: "/"

      - name: "test: put"
        uses: ModelingValueGroup/sync-s3-action@master
        with:
          token          : "${{ secrets.GITHUB_TOKEN }}"
          trigger_token  : "${{ secrets.RETRIGGER_TOKEN }}"
          access_key     : "${{ secrets.SCALEWAY_ACCESS_KEY }}"
          secret_key     : "${{ secrets.SCALEWAY_SECRET_KEY }}"
          bucket         : "${{ env.TEMP_BUCKET }}"
          cmd            : "put"
          local_dir      : "test-dir-put"
          s3_dir         : "s3-dir"

      - name: "test: get"
        uses: ModelingValueGroup/sync-s3-action@master
        with:
          token          : "${{ secrets.GITHUB_TOKEN }}"
          trigger_token  : "${{ secrets.RETRIGGER_TOKEN }}"
          access_key     : "${{ secrets.SCALEWAY_ACCESS_KEY }}"
          secret_key     : "${{ secrets.SCALEWAY_SECRET_KEY }}"
          bucket         : "${{ env.TEMP_BUCKET }}"
          cmd            : "get"
          local_dir      : "test-dir-get"
          s3_dir         : "s3-dir"

      - name: "test: cleanup"
        run: |
          #
          . buildToolsMeme.sh "${{ secrets.GITHUB_TOKEN }}"

          conf="$(prepS3cmd "https://s3.nl-ams.scw.cloud" "${{ secrets.SCALEWAY_ACCESS_KEY }}" "${{ secrets.SCALEWAY_SECRET_KEY }}")"
          s3cmd --config="$conf" rm "s3://${{ env.TEMP_BUCKET }}/s3-dir/test123"
          s3cmd --config="$conf" rm "s3://${{ env.TEMP_BUCKET }}/s3-dir"
          s3cmd --config="$conf" rb "s3://${{ env.TEMP_BUCKET }}"

      - name: "test: check"
        run: |
          if [[ "$(cat test-dir-put/test123)" != "$(cat test-dir-get/test123)" ]]; then
            echo "::error::failed to get the test file"
            exit 88
          fi
          echo "# all ok"

