name: test
on:
  push
jobs:
  test:
    runs-on: [ubuntu-latest]
    steps:
      - name: "checkout"
        uses: actions/checkout@v1

      - name: "test"
        run: |
          set -x
          mkdir test-dir
          echo test123 >test-dir/test123

                INPUT_HOST=
              INPUT_REGION=
              INPUT_BUCKET="test-bucket"
          INPUT_ACCESS_KEY="${{ secrets.SCALEWAY_ACCESS_KEY }}"
          INPUT_SECRET_KEY="${{ secrets.SCALEWAY_SECRET_KEY }}"
              INPUT_S3_DIR=s3-dir

          INPUT_LOCAL_DIR=test-dir
          INPUT_CMD=put
          . ./entrypoint.sh

          INPUT_LOCAL_DIR=test-dir-2
          INPUT_CMD=get
          . ./entrypoint.sh

          s3cmd_ rm "s3://test-bucket/s3-dir"
          s3cmd_ rb "s3://test-bucket"

          if [[ "$(cat test-dir/test123)" != "$(cat test-dir-2/test123)" ]]; then
            echo "::error::failed to get the test file"
            exit 88
          fi

          echo "# all ok"
