name: test
on:
  push
jobs:
  test:
    runs-on: [ubuntu-latest]
    steps:
      - name: "checkout"
        uses: actions/checkout@v1

      - name: "install s3cmd"
        run: |
          sudo apt-get update
          sudo apt-get install -y s3cmd

      - name: "test: prepare"
        run: |
          mkdir test-dir-put
          echo test123 > test-dir-put/test123

      - name: "test: put with branch dir"
        uses: ModelingValueGroup/sync-s3-action@master
        with:
          access_key     : "${{ secrets.SCALEWAY_ACCESS_KEY }}"
          secret_key     : "${{ secrets.SCALEWAY_SECRET_KEY }}"
          bucket         : "mvg-test-perm2"
          cmd            : "put"
          local_dir      : "."
          s3_dir         : "/"
          s3_dir_branched: "true"

      - name: "test: put"
        uses: ModelingValueGroup/sync-s3-action@master
        with:
          access_key     : "${{ secrets.SCALEWAY_ACCESS_KEY }}"
          secret_key     : "${{ secrets.SCALEWAY_SECRET_KEY }}"
          bucket         : "mvg-test-temp"
          cmd            : "put"
          local_dir      : "test-dir-put"
          s3_dir         : "s3-dir"

      - name: "test: get"
        uses: ModelingValueGroup/sync-s3-action@master
        with:
          access_key     : "${{ secrets.SCALEWAY_ACCESS_KEY }}"
          secret_key     : "${{ secrets.SCALEWAY_SECRET_KEY }}"
          bucket         : "mvg-test-temp"
          cmd            : "get"
          local_dir      : "test-dir-get"
          s3_dir         : "s3-dir"

      - name: "test: cleanup"
        run: |
          #
          INPUT_ACCESS_KEY="${{ secrets.SCALEWAY_ACCESS_KEY }}"
          INPUT_SECRET_KEY="${{ secrets.SCALEWAY_SECRET_KEY }}"
          . ./functions.sh
          handleArgs
          s3cmd_ rm "s3://mvg-test-temp/s3-dir/test123"
          s3cmd_ rm "s3://mvg-test-temp/s3-dir"
          s3cmd_ rb "s3://mvg-test-temp"

      - name: "test: check"
        run: |
          if [[ "$(cat test-dir-put/test123)" != "$(cat test-dir-get/test123)" ]]; then
            echo "::error::failed to get the test file"
            exit 88
          fi
          echo "# all ok"

